//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWTarefas.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SWTarefasMessagesExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SWTarefasMessagesExceptions() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWTarefas.Resources.Resources.SWTarefasMessagesExceptions", typeof(SWTarefasMessagesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de conclusão prevista tem que ser inferior ou igual a data de conclusão realizada..
        /// </summary>
        public static string DataConclusaoInferiorDataPrevista {
            get {
                return ResourceManager.GetString("DataConclusaoInferiorDataPrevista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de conclusão realizada tem que ser superior ou igual a data de conclusão prevista..
        /// </summary>
        public static string DataConclusaoSuperiorDataPrevista {
            get {
                return ResourceManager.GetString("DataConclusaoSuperiorDataPrevista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo descrição tem no máximo 400 cacteres..
        /// </summary>
        public static string DescricaoMaximoCaracteres {
            get {
                return ResourceManager.GetString("DescricaoMaximoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Problema ao converter a tarefa..
        /// </summary>
        public static string ProblemaConverterTarefa {
            get {
                return ResourceManager.GetString("ProblemaConverterTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status inválido (1 - Concluída, 2 - Pendente)..
        /// </summary>
        public static string StatusInvalido {
            get {
                return ResourceManager.GetString("StatusInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo status não pode fica vazio..
        /// </summary>
        public static string StatusVazio {
            get {
                return ResourceManager.GetString("StatusVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A tarefa não existe..
        /// </summary>
        public static string TarefaNaoExiste {
            get {
                return ResourceManager.GetString("TarefaNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo tarefaid não pode fica vazio..
        /// </summary>
        public static string TarefaVazia {
            get {
                return ResourceManager.GetString("TarefaVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo título tem no máximo 100 cacteres..
        /// </summary>
        public static string TItuloMaximoCaracteres {
            get {
                return ResourceManager.GetString("TItuloMaximoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo título não pode fica vazio..
        /// </summary>
        public static string TituloVazio {
            get {
                return ResourceManager.GetString("TituloVazio", resourceCulture);
            }
        }
    }
}
